# Generated by Django 4.0.3 on 2022-04-19 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_alter_article_body_alter_article_summary_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='date',
            new_name='date_added',
        ),
    ]
