# Generated by Django 4.0.3 on 2022-04-19 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_rename_date_comment_date_added'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='name',
            new_name='comment',
        ),
    ]
